<div class="container mx-auto mt-5 font-mono">
    <h1 class="text-4xl font-bold m-5 text-center capitalize">
    Una simple <span class="italic underline decoration-2">TO-DO</span> list
  </h1>

<div class="container"> 
<div class="flex flex-col mt-10">
    <div class="text-2xl uppercase">Descripción
<form action= "<?php echo WEB_ROOT ?>/tareas/nuevaTarea" method="post">
    <input class="text-lg border p-2 pr-10 mr-2 shadow-md rounded italic w-96 my-5" type="text" name="todo_name" placeholder="Ingresar tarea">
    <button class="text-lg bg-green-500 hover:bg-green-700 rounded font-semibold uppercase py-2 px-3 text-white" type="submit">Agregar Tarea</button>
</form>
</div>
<br>
<div class="flex flex-col mb-10">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table class="min-w-full text-center">
                        <thead class="border-b bg-gray-50">
                <tr>
                    
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">Nro</th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">Despcripción</th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">Estado</th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">Fecha</th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">Hora Ini</th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">Hora Fin</th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">Usuario</th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">Acciones</th>
                </tr>
            </thead>
            <tbody class="text-base uppercase">
            <?php
            //var_dump($this);
            if(sizeof($this->tareas)>0){
            
            for($i=0; $i<sizeof($this->tareas); $i++){
            $tarea = $this->tareas[$i];

            ?>
                <tr>
                    <th></th>
                            
                    <td><p><?php echo $tarea->getTitulo(); ?> </p></td>
                    <td><p><?php echo $tarea->getEstado(); ?> </p></td>
                    <td><p><?php echo $tarea->getDate(); ?> </p></td>
                    <td><p><?php echo $tarea->getHoraInicio(); ?> </p></td>
                    <td><p><?php echo $tarea->getHoraFin(); ?> </p></td>
                    <td><p><?php echo $tarea->getUsuario(); ?> </p></td>
                    <td class="w-48 pb-2">
                        <div class="flex justify-around">
                        <form action="<?php echo WEB_ROOT ?>/tareas/listarTarea" method="post">
                        <input type="hidden" name="titulo" value="<?php echo $tarea->getTitulo(); ?>">
                        <button class="text-base bg-orange-500 hover:bg-orange-700 rounded font-semibold uppercase py-1 px-5 text-white m-2">Editar</a>
                        </form>
                        <form action="<?php echo WEB_ROOT ?>/tareas/eleminarTarea" method="post">
                        <input type="hidden" name="titulo" value="<?php echo $tarea->getTitulo(); ?>">
                         <button class="text-base bg-red-500 hover:bg-red-700 rounded font-semibold uppercase py-1 px-2 text-white m-2">Eliminar</a>
                        </form>
                        </div>
                        </td>
        
        
            <?php
            }

            }else{
            ?>
            <p>No hay tareas disponibles</p>
            <?php
            }
    
            ?>         
            </tr>       
            </tbody>

    
        </table>
    </div>
</div>
</div>
</div>
</div>
    